fields:
  - name: name_uk
    type: fake
    value: '{productname}'

  - name: name_en
    type: dependent
    value: name_uk

  - name: slug
    type: fake
    value: '{uuid}'

  - name: category
    type: relation
    value: categories

  - name: brand
    type: relation
    value: brands

  - name: description_uk
    type: fake
    value: '{sentence:10}'

  - name: description_en
    type: dependent
    value: description_uk

  - name: price
    type: fake
    value: '{number:200,100000}'

  - name: stockStatus
    type: fake
    value: '{randomstring:[inStock, outOfStock, preOrder]}'

  - name: status
    type: custom
    value: active
